package cn.java.entity;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;

import cn.java.validator.AccountNumberValidator;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.id
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.adminuser
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    @NotEmpty(message = "账号不能为空")
    @Length(min=8,max=16,message="账号长度不正确")
    @Pattern(regexp="^[a-zA-Z]+[a-zA-Z0-9]*", message="账号由字母数字组成，必须以字母开头")
    private String adminuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.adminpass
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     * @NotNull(message="密码不能为空")
     *  @Length(min=6,max=16,message="密码长度不正确")
     */
    @NotNull(message="密码不能为空")
    @Length(min=6,max=16,message="密码长度不正确")
    @Pattern(regexp="^[~!@#$%^&*()_+-`·\\.////<>,{}:a-zA-Z0-9\\|'\"]*", message="密码由字母数字符号组成")
    private String adminpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.authority
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    @NotNull(message="权限不能为空")
    private Integer authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.id
     *
     * @return the value of admin_user.id
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.id
     *
     * @param id the value for admin_user.id
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.adminuser
     *
     * @return the value of admin_user.adminuser
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public String getAdminuser() {
        return adminuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.adminuser
     *
     * @param adminuser the value for admin_user.adminuser
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public void setAdminuser(String adminuser) {
        this.adminuser = adminuser == null ? null : adminuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.adminpass
     *
     * @return the value of admin_user.adminpass
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public String getAdminpass() {
        return adminpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.adminpass
     *
     * @param adminpass the value for admin_user.adminpass
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public void setAdminpass(String adminpass) {
        this.adminpass = adminpass == null ? null : adminpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.authority
     *
     * @return the value of admin_user.authority
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.authority
     *
     * @param authority the value for admin_user.authority
     *
     * @mbg.generated Sun Oct 14 23:45:50 CST 2018
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

	@Override
	public String toString() {
		return "AdminUser [id=" + id + ", adminuser=" + adminuser + ", adminpass=" + adminpass + ", authority="
				+ authority + "]";
	}
    
}