package cn.java.entity;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import cn.java.tool.CustomDateSerializer;

public class DormitorNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_notice.id
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_notice.date
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_notice.text
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_notice.texthtml
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    private String texthtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_notice.id
     *
     * @return the value of dormitory_notice.id
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_notice.id
     *
     * @param id the value for dormitory_notice.id
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_notice.date
     *
     * @return the value of dormitory_notice.date
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_notice.date
     *
     * @param date the value for dormitory_notice.date
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_notice.text
     *
     * @return the value of dormitory_notice.text
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_notice.text
     *
     * @param text the value for dormitory_notice.text
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_notice.texthtml
     *
     * @return the value of dormitory_notice.texthtml
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public String getTexthtml() {
        return texthtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_notice.texthtml
     *
     * @param texthtml the value for dormitory_notice.texthtml
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    public void setTexthtml(String texthtml) {
        this.texthtml = texthtml == null ? null : texthtml.trim();
    }

	@Override
	public String toString() {
		return "DormitorNotice [id=" + id + ", date=" + date + ", text=" + text + ", texthtml=" + texthtml + "]";
	}
    
}