package cn.java.entity;

public class DormitoryRoomManNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_roommannum.id
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_roommannum.num
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_roommannum.pid
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_roommannum.id
     *
     * @return the value of dormitory_roommannum.id
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_roommannum.id
     *
     * @param id the value for dormitory_roommannum.id
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_roommannum.num
     *
     * @return the value of dormitory_roommannum.num
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_roommannum.num
     *
     * @param num the value for dormitory_roommannum.num
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_roommannum.pid
     *
     * @return the value of dormitory_roommannum.pid
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_roommannum.pid
     *
     * @param pid the value for dormitory_roommannum.pid
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

	@Override
	public String toString() {
		return "DormitoryRoomManNum [id=" + id + ", num=" + num + ", pid=" + pid + "]";
	}
}