package cn.java.entity;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;

public class DormitoryRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_room.id
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_room.name
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    @NotEmpty(message = "宿舍号不能为空")
    @Pattern(regexp="^[0-9]*", message="宿舍号只能由数字组成")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_room.floor
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_room.pid
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_room.id
     *
     * @return the value of dormitory_room.id
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_room.id
     *
     * @param id the value for dormitory_room.id
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_room.name
     *
     * @return the value of dormitory_room.name
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_room.name
     *
     * @param name the value for dormitory_room.name
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_room.floor
     *
     * @return the value of dormitory_room.floor
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_room.floor
     *
     * @param floor the value for dormitory_room.floor
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_room.pid
     *
     * @return the value of dormitory_room.pid
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_room.pid
     *
     * @param pid the value for dormitory_room.pid
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

	@Override
	public String toString() {
		return "DormitoryRoom [id=" + id + ", name=" + name + ", floor=" + floor + ", pid=" + pid + "]";
	}
    
}