package cn.java.entity;

import java.util.Date;

public class DormitoryAbout {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.id
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.pid
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.month
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Date month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.surpelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Double surpelectric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.amountelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Double amountelectric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_about.hygiene
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    private Double hygiene;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.id
     *
     * @return the value of dormitory_about.id
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.id
     *
     * @param id the value for dormitory_about.id
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.pid
     *
     * @return the value of dormitory_about.pid
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.pid
     *
     * @param pid the value for dormitory_about.pid
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.month
     *
     * @return the value of dormitory_about.month
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.month
     *
     * @param month the value for dormitory_about.month
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.surpelectric
     *
     * @return the value of dormitory_about.surpelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Double getSurpelectric() {
        return surpelectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.surpelectric
     *
     * @param surpelectric the value for dormitory_about.surpelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setSurpelectric(Double surpelectric) {
        this.surpelectric = surpelectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.amountelectric
     *
     * @return the value of dormitory_about.amountelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Double getAmountelectric() {
        return amountelectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.amountelectric
     *
     * @param amountelectric the value for dormitory_about.amountelectric
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setAmountelectric(Double amountelectric) {
        this.amountelectric = amountelectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_about.hygiene
     *
     * @return the value of dormitory_about.hygiene
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public Double getHygiene() {
        return hygiene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_about.hygiene
     *
     * @param hygiene the value for dormitory_about.hygiene
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    public void setHygiene(Double hygiene) {
        this.hygiene = hygiene;
    }

	@Override
	public String toString() {
		return "DormitoryAbout [id=" + id + ", pid=" + pid + ", month=" + month + ", surpelectric=" + surpelectric
				+ ", amountelectric=" + amountelectric + ", hygiene=" + hygiene + "]";
	}
    
}