package cn.java.entity;

public class DormitoryDdmintext {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_admintext.id
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_admintext.title
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_admintext.date
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_admintext.text
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_admintext.id
     *
     * @return the value of dormitory_admintext.id
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_admintext.id
     *
     * @param id the value for dormitory_admintext.id
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_admintext.title
     *
     * @return the value of dormitory_admintext.title
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_admintext.title
     *
     * @param title the value for dormitory_admintext.title
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_admintext.date
     *
     * @return the value of dormitory_admintext.date
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_admintext.date
     *
     * @param date the value for dormitory_admintext.date
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_admintext.text
     *
     * @return the value of dormitory_admintext.text
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_admintext.text
     *
     * @param text the value for dormitory_admintext.text
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}