package cn.java.entity;

public class Dormitory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.id
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.name
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.id
     *
     * @return the value of dormitory.id
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.id
     *
     * @param id the value for dormitory.id
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.name
     *
     * @return the value of dormitory.name
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.name
     *
     * @param name the value for dormitory.name
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "Dormitory [id=" + id + ", name=" + name + "]";
	}
}