package cn.java.entity;

public class SchoolMajorClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_majorclass.id
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_majorclass.name
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_majorclass.pid
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_majorclass.id
     *
     * @return the value of school_majorclass.id
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_majorclass.id
     *
     * @param id the value for school_majorclass.id
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_majorclass.name
     *
     * @return the value of school_majorclass.name
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_majorclass.name
     *
     * @param name the value for school_majorclass.name
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_majorclass.pid
     *
     * @return the value of school_majorclass.pid
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_majorclass.pid
     *
     * @param pid the value for school_majorclass.pid
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

	@Override
	public String toString() {
		return "SchoolMajorClass [id=" + id + ", name=" + name + ", pid=" + pid + "]";
	}

}