package cn.java.entity;

public class SchoolMajor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_major.id
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_major.name
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_major.pid
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_major.id
     *
     * @return the value of school_major.id
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    
    /**
     * ∂‘”¶∞‡º∂
     * @return
     */
    
    private SchoolMajorClass schoolMajorClass;
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_major.id
     *
     * @param id the value for school_major.id
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_major.name
     *
     * @return the value of school_major.name
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_major.name
     *
     * @param name the value for school_major.name
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_major.pid
     *
     * @return the value of school_major.pid
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_major.pid
     *
     * @param pid the value for school_major.pid
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

	public SchoolMajorClass getSchoolMajorClass() {
		return schoolMajorClass;
	}

	public void setSchoolMajorClass(SchoolMajorClass schoolMajorClass) {
		this.schoolMajorClass = schoolMajorClass;
	}

	@Override
	public String toString() {
		return "SchoolMajor [id=" + id + ", name=" + name + ", pid=" + pid + ", schoolMajorClass=" + schoolMajorClass
				+ "]";
	}

	
    
}