package cn.java.entity;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;

public class StudentUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_user.id
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_user.user
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    @NotEmpty(message = "账号不能为空")
    @Length(min=8,max=16,message="账号长度不正确")
    @Pattern(regexp="^[0-9]*", message="账号只能由数字组成")
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_user.pass
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    @NotNull(message="密码不能为空")
    @Length(min=6,max=16,message="密码长度不正确")
    @Pattern(regexp="^[~!@#$%^&*()_+-`·\\.////<>,{}:a-zA-Z0-9\\|'\"]*", message="密码由字母数字符号组成")
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_user.id
     *
     * @return the value of student_user.id
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_user.id
     *
     * @param id the value for student_user.id
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_user.user
     *
     * @return the value of student_user.user
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_user.user
     *
     * @param user the value for student_user.user
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_user.pass
     *
     * @return the value of student_user.pass
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_user.pass
     *
     * @param pass the value for student_user.pass
     *
     * @mbg.generated Sun Oct 21 23:25:06 CST 2018
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

	@Override
	public String toString() {
		return "StudentUser [id=" + id + ", user=" + user + ", pass=" + pass + "]";
	}
    
}