package cn.java.dao.admin;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.java.entity.DormitoryRoom;

public interface DormitoryRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int insert(DormitoryRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    DormitoryRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    List<DormitoryRoom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int updateByPrimaryKey(DormitoryRoom record);
    
    /**
     * 	°´Ìõ¼þ²éÑ¯ËÞÉá
     */
    List<DormitoryRoom> selectroomAll(Integer pid);
    
    /**
     * 	ÅÐ¶ÏËÞÉáºÅ´æÔÚ·ñ
     */
    DormitoryRoom selectroomname(@Param("name") String name,@Param("pid") Integer pid);
    
}