package cn.java.dao.admin;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.java.entity.DormitoryAbout;
import cn.java.entity.JsonBean;
import cn.java.entity.StudentPerson;

public interface DormitoryAboutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_about
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_about
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    int insert(DormitoryAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_about
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    DormitoryAbout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_about
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    List<DormitoryAbout> selectAll();
    
    List<DormitoryAbout> selectAllDesc(Integer pid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_about
     *
     * @mbg.generated Thu Nov 01 15:32:57 CST 2018
     */
    int updateByPrimaryKey(DormitoryAbout record);
    
    List<DormitoryAbout> selecByPidtAll(Integer pid);
    
    int deleteByPidAll(Integer pid);
    
    DormitoryAbout selectAllDescTop(Integer pid);
    
    int updatehygiene(@Param("list") List<JsonBean> list);
    
    List<DormitoryAbout> selectAllGroupby();
    
	int updatemongthday(@Param("list") List<DormitoryAbout> list);
	
	int insertmore(@Param("list") List<DormitoryAbout> list);
}