package cn.java.dao.admin;

import java.util.List;

import cn.java.entity.DormitoryDdmintext;

public interface DormitoryDdmintextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admintext
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admintext
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    int insert(DormitoryDdmintext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admintext
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    DormitoryDdmintext selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admintext
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    List<DormitoryDdmintext> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_admintext
     *
     * @mbg.generated Tue Oct 30 23:52:20 CST 2018
     */
    int updateByPrimaryKey(DormitoryDdmintext record);
    
    /**
     * 	按题目搜索资讯
     */
    List<DormitoryDdmintext> selectByTitleAll(String title);
}