package cn.java.dao.admin;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cn.java.entity.DormitoryRoom;

public interface DormitoryRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int insert(DormitoryRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    DormitoryRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    List<DormitoryRoom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_room
     *
     * @mbg.generated Tue Oct 23 13:15:57 CST 2018
     */
    int updateByPrimaryKey(DormitoryRoom record);
    
    /**
     * 	按条件查询宿舍
     */
    List<DormitoryRoom> selectroomAll(Integer pid);
    
    /**
     * 	按条件查询宿舍带人数
     */
    List<Map<Object,Object>> selectroomAllnum(Integer pid);
    /**
     * 	判断宿舍号存在否
     */
    DormitoryRoom selectroomname(@Param("name") String name,@Param("pid") Integer pid);
    
    /**
     * 按带卫生宿舍查询
     */
    List<Object> selecthygiene(Integer pid);
    
}