package cn.java.dao.admin;


import java.util.List;

import cn.java.entity.Dormitory;

public interface DormitoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    int insert(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    Dormitory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    List<Dormitory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated Mon Oct 22 19:04:55 CST 2018
     */
    int updateByPrimaryKey(Dormitory record);
    
    /**
     * ÅÐ¶ÏËÞÉáÂ¥Ãû×Ö
     */
    Dormitory selectdormitoryname(String name);
}