package cn.java.dao.admin;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.java.entity.DormitoryRoomManNum;

public interface DormitoryRoomManNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_roommannum
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_roommannum
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    int insert(DormitoryRoomManNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_roommannum
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    DormitoryRoomManNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_roommannum
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    List<DormitoryRoomManNum> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_roommannum
     *
     * @mbg.generated Sat Oct 27 15:45:57 CST 2018
     */
    int updateByPrimaryKey(DormitoryRoomManNum record);
    
    /**
     * 按pid删除对应宿舍
     */
    int deletebypid(@Param("pid") Integer pid);
    
    /**
     * num自增1
     */
    int addnum(Integer pid);
    
    /**
     * num自减1
     */
    int subnum(Integer pid);
}