package cn.java.dao.admin;


import java.util.List;

import cn.java.entity.DormitorNotice;

public interface DormitorNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_notice
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_notice
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    int insert(DormitorNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_notice
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    DormitorNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_notice
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    List<DormitorNotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_notice
     *
     * @mbg.generated Tue Oct 30 14:47:38 CST 2018
     */
    int updateByPrimaryKey(DormitorNotice record);
}