package cn.java.dao.admin;


import java.util.List;

import cn.java.entity.SchoolMajorClass;

public interface SchoolMajorClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_majorclass
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_majorclass
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    int insert(SchoolMajorClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_majorclass
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    SchoolMajorClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_majorclass
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    List<SchoolMajorClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_majorclass
     *
     * @mbg.generated Wed Oct 17 09:49:42 CST 2018
     */
    int updateByPrimaryKey(SchoolMajorClass record);
    
    List<SchoolMajorClass> selectPid(Integer pid);
}