package cn.java.dao.admin;


import java.util.List;

import cn.java.entity.SchoolCollege;

public interface SchoolCollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_college
     *
     * @mbg.generated Wed Oct 17 09:42:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_college
     *
     * @mbg.generated Wed Oct 17 09:42:35 CST 2018
     */
    int insert(SchoolCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_college
     *
     * @mbg.generated Wed Oct 17 09:42:35 CST 2018
     */
    SchoolCollege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_college
     *
     * @mbg.generated Wed Oct 17 09:42:35 CST 2018
     */
    List<SchoolCollege> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_college
     *
     * @mbg.generated Wed Oct 17 09:42:35 CST 2018
     */
    int updateByPrimaryKey(SchoolCollege record);
    
    /**
     * 查询所有，包括子序列
     * @return
     */
    List<SchoolCollege> selectAllInMajor();
    
}