package cn.java.dao.admin;


import java.util.List;

import cn.java.entity.SchoolMajor;

public interface SchoolMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    int insert(SchoolMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    SchoolMajor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    List<SchoolMajor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major
     *
     * @mbg.generated Wed Oct 17 09:46:35 CST 2018
     */
    int updateByPrimaryKey(SchoolMajor record);
    
    List<SchoolMajor> selectByPid(Integer pid);
}