package cn.java.dao.admin;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.java.entity.StudentPerson;

public interface StudentPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_person
     *
     * @mbg.generated Mon Oct 22 14:43:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_person
     *
     * @mbg.generated Mon Oct 22 14:43:00 CST 2018
     */
    int insert(StudentPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_person
     *
     * @mbg.generated Mon Oct 22 14:43:00 CST 2018
     */
    StudentPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_person
     *
     * @mbg.generated Mon Oct 22 14:43:00 CST 2018
     */
    List<StudentPerson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_person
     *
     * @mbg.generated Mon Oct 22 14:43:00 CST 2018
     */
    int updateByPrimaryKey(StudentPerson record);
    
    /**
     * 	查询学院学生
     */
    List<StudentPerson> selectmajorclassAll(@Param("college") Integer college,@Param("major") Integer major,@Param("majorclass") Integer majorclass);
    
    /**
     * 	按学号查询学生
     */
    StudentPerson selectonebyid(String id);
    
    /**
     * 	根据学号删除学生
     */
    int deleteonebyid(String id);
    
    /**
     * 	根据学号修改学生
     */
    int updateonebyid(StudentPerson record);
    
    /**
     * 	查询一个宿舍学生
     */
    List<StudentPerson> selectroomAll(@Param("dormitory") Integer dormitory,@Param("room") Integer room);
    
    /**
     * 	根据宿舍查询学生
     */
    List<StudentPerson> selectByroomnum(Integer room);
    
    int updatemoreroom(@Param("list") List<StudentPerson> list);
}